### ISSUE TITLE
Triage Input from Open Science Call

### ISSUE THREAD

**Issue by LGro** [freeyourscience/freeyourscience#26]
TODO: Triage the points collected below.

https://pad.okfn.de/p/Open_Science_AG_Public_Call_067

Open topics:
- [x] explain better the differences between submitted, accepted, published version
- [x] #34 link the open access paper / semantic scholar paper details page instead of / in addition to the doi link (potentially paywalled)
- [ ] Leverage Open Science AG channels (e.g. Konrad, podcasts, mailinglist) for spreading the word once confident about the current version
- [ ] Tell users what they can do about "publications with issues"
- [ ] make freeyourscience citable
  - [ ] [citable repo with zenodo](https://guides.github.com/activities/citable-code/)
  - [ ] citable website?

Specific issues:
- [x] #36 ORCID: 0000-0002-2401-6862 (Publication with Issues)
- [x] #34 This paper: https://journals.aps.org/prb/abstract/10.1103/PhysRevB.97.085144 , I used the search for DOI: 10.1103/PhysRevB.97.085144  . The paper is available on arxiv.org, maybe it means that? But then the link should point arxiv.org not to the APS Journal.

**Comment by erkannt** [comment]
Regarding versions see glossary here: https://v2.sherpa.ac.uk/romeo/about.html
