### ISSUE TITLE
Log retention and export

### ISSUE THREAD

**Issue by LGro** [freeyourscience/freeyourscience#58]
store logs (externally or at GCP) for analysis purposes (exportable!)

## Findings

- logs are retained for 30 days by default https://cloud.google.com/logging/docs/routing/overview
- default retention is free https://cloud.google.com/stackdriver/pricing#logging-pricing-summary
- can be dumped from the _log bucket_ using cli https://cloud.google.com/sdk/gcloud/reference/logging/read
- for long term storage the docs recommend adding an additional _log sink_ that dumps the logs into _cloud storage_ https://cloud.google.com/logging/docs/export#supported-destinations
- Comparing log storage pricing and _cloud storage_ pricing, the latter is cheaper if you use cold-line or archival tiers. One does pay for network egress in those. https://cloud.google.com/storage/pricing
- Logging ingestion is free for the first 50GiB per month. Retention beyond 30 days costs $0.01/GiB (per month?).
- `gcloud logging read "" --bucket=_Default --location=global  --view=_Default --limit=1000 --format=json` only produced 353 log lines, even though we have over 40.000 logs in total according to the log explorer. Maximum dump from the explorer we can download is 10.000. Going to look into alternative ways of getting our logs.

## ToDo

- [x] check that logs can be exported using gcp cli __FAILED__
- [x] set retention to 2 years
- [x] see if we can dump logs for prod as json to a low cost bucket
  - [x] set up sink and bucket with terraform
  - [x] check if prod logs show up in bucket
